### ISSUE TITLE
Install Wrapper

### ISSUE THREAD

**Issue by fluxlabs** [itglue/powershellwrapper#11]
Not sure of the location to load the wrapper on Server 2008/12 .. the default path doesnt exist. Getting an error when loading from C:\Windows\System32\WindowsPowerShell\v1.0\Modules.
<img width="1005" alt="screenshot 2018-04-10 22 26 46" src="https://user-images.githubusercontent.com/211150/38594939-82073fb6-3d0e-11e8-94bd-5e0df0ffb852.png">

**Comment by ecspresso** [comment]
Which PowerShell version do you have installed? As someone discussed here (https://github.com/MichaelGrafnetter/DSInternals/issues/28), it is because you are running version 2.

Have a look at this link. https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-windows-powershell?view=powershell-6#upgrading-existing-windows-powershell
