### ISSUE TITLE
web_error return variable is not valid

### ISSUE THREAD

**Issue by DarrenWhite99** [itglue/powershellwrapper#66]
**Steps to reproduce**
Call any function that returns an error. 
Example: Get-ITGlueConfigurations -id 12345

**Expected behavior**

The variable $web_error should contain the error output.

**Actual behavior**

$web_error is not returned.
This is because the -ErrorVariable parameter expects the bare name for the variable, without the $. Example:
-ErrorVariable web_error

Assuming that the intent is to allow users to define their own variable name, where $web_error='my_error_variable', it should be called as:
-ErrorVariable $($web_error)
which would put the error output into $my_error_variable

I think using $web_error as the return variable is fine, but perhaps the other behavior would be desired.

**Comment by ecspresso** [comment]
I suggest that we fix this while implementing #151.

**Comment by davidhaymond** [comment]
I did some digging since I'm not too familiar with -ErrorVariable, and I think we should remove it entirely since it is a [common parameter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters); PowerShell does all the wiring automatically. Specifically, see this note in the previously linked documentation:

> The custom error variable contains all errors generated by the command, including errors from calls to nested functions or scripts.

So there is no need to pass the custom variable to `Invoke-RestMethod` since PowerShell handles that for us.

**Comment by ecspresso** [comment]
I removed `-ErrorVariable` in #151.
